create table patients (
    id int GENERATED BY DEFAULT AS IDENTITY, 
    name varchar, 
    date_of_birth date
);

create table medical_histories (
    id int generated by default as identity, 
    admitted_at timestamp, patient_id int, 
    status varchar, 
    primary key(id)
);

create table treatments (
    id int generated by default as identity primary key, 
    type varchar, 
    name varchar
);

create table invoice_items (
    id int generated by default as identity primary key, 
    unit_price decimal, 
    quantity int, 
    total_price decimal, 
    invoice_id int, treatment_id int
);

create table invoices (
    id int generated by default as identity primary key, 
    total_amount decimal, 
    generated_at timestamp, 
    payed_at timestamp, 
    medical_history_id int
);

-- Add foreign keys to existing tables
ALTER TABLE medical_histories ADD FOREIGN KEY(patient_id) REFERENCES patients(id);
ALTER TABLE invoices ADD FOREIGN KEY(medical_history_id) REFERENCES medical_histories(id);

ALTER TABLE invoice_items ADD FOREIGN KEY (invoice_id) REFERENCES invoices(id);
ALTER TABLE invoice_items ADD FOREIGN KEY (treatment_id) REFERENCES treatments(id);

-- Create join table
create table medical_historie_treatments (
    medical_history_id int,
    treatment_id int,
    primary key(medical_history_id, treatment_id)
);

